"""empty message

Revision ID: 05a1b5450e81
Revises: 11820198e362
Create Date: 2022-07-05 23:15:36.981953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05a1b5450e81'
down_revision = '11820198e362'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('key_strokes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=15), nullable=False),
    sa.Column('location', sa.String(length=30), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('key_strokes')
    # ### end Alembic commands ###
