"""empty message

Revision ID: 11820198e362
Revises: 57c216894b64
Create Date: 2022-07-04 18:53:22.551349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11820198e362'
down_revision = '57c216894b64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('body', sa.String(length=400), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blogs')
    # ### end Alembic commands ###
