"""empty message

Revision ID: 33c81edb9fb9
Revises: e1e38f3fb4f2
Create Date: 2022-07-04 18:36:44.743125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33c81edb9fb9'
down_revision = 'e1e38f3fb4f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('body', sa.String(length=400), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'body')
    # ### end Alembic commands ###
