"""empty message

Revision ID: e1e38f3fb4f2
Revises: 
Create Date: 2022-07-04 18:36:20.516099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1e38f3fb4f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('body', sa.VARCHAR(length=100), nullable=False))
    # ### end Alembic commands ###
