"""empty message

Revision ID: e7f8bc199923
Revises: 05a1b5450e81
Create Date: 2022-07-05 23:47:17.979718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7f8bc199923'
down_revision = '05a1b5450e81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('key_strokes', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('key_strokes', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
