"""empty message

Revision ID: e93b2ed0bc0a
Revises: e7f8bc199923
Create Date: 2022-07-05 23:48:00.380302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e93b2ed0bc0a'
down_revision = 'e7f8bc199923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('key_strokes', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('key_strokes', 'timestamp')
    # ### end Alembic commands ###
